title: "Apunts de Desenvolupament Web"
description: "HTML, CSS i JavaScript"
remote_theme: just-the-docs/just-the-docs

# Opcional: activem cerca
plugins:
  - jekyll-seo-tag

# Navegaci√≥
just-the-docs:
  logo: ""
